### ISSUE TITLE
toDO

### ISSUE THREAD

**Issue by cacaiocamp** [cacaiocamp/joyOSCMapper#1]
Changes:
- [x] add an ofOscSender per Joycon, to make netAddress and port configuration individual
- [x] modify all joycons drawing representations to ofPaths and save their values as 'Joycon' atributes

New:
- [ ] add general config. window
- [ ] add individual Joycon config window
- [x] implement clickable joycons button drawings, using ofPath.getOutline() + ofPolyline.inside() to identify the clicks. When the buttons are clicked, an ofBitmapString with their full respective osc message must be shown in the mouse pointer
- [x] implement oscSend for virtual joycons
- [x] implement stick as D-pad
- [x] implement stick polar coordinates
- [x] add 'oscOnly' button, that stops drawing everything but continues to send the osc messages
- [x] implement a oscReciever, that work as a toggle for the 'oscOnly' button

What to add on config windows?
1. use/draw raw and/or cooked graphs
2. change osc address, port and tags
3. change minStickStep
4. use stick as D-pad/polar coordinates
5. chance stickAsDpadProp
6. change IMUVectorsSize
7. save and load preferences

**Comment by cacaiocamp** [comment]
Closing issue after publication, with the last implementations of this issue also published on README.md.
